eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: true
    instance:
      preferIpAddress: true
management:
   security:
      enabled: false
urlCamunda: ${URL_CAMUNDA:http://34.68.237.95:8080/engine-rest}
aaiUrlServiceInstance: ${AAI_SI_URL:http://localhost:8092}
osmUrlServiceInstance: ${URL_OSM_NSLCM:http://34.69.239.30:8087}
aaiUrlGenerifVnf: ${AAI_GV_URL:http://localhost:8085}
osmUrlVnfInstance: ${OSM_VNF_URL:http://localhost:8088}
recipients: ${RECIPIENT:eduardo.tapia@telefonica.com}
jiraMediatorAPI: ${JIRA_MD_API:http://35.202.179.72:80}
facebookMediatorAPI: ${FB_MD_API:http://104.154.198.186:80}
woProjectId: ${WO_PROJ_ID:124554052096}
