eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: true
osm:
  connection:
    protocol: ${OSM_PROTOCOL:https://}
    domain: ${OSM_DOMAIN:35.193.155.192}
    port: ${OSM_PORT:9999}
    user: ${OSM_USER:admin}
    passwd: ${OSM_PASSWD:admin}
