eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: true
urlCamunda: ${URL_CAMUNDA:http://34.68.237.95:8080/engine-rest}
aaiUrlServiceInstance: ${AAI_SI_URL:http://localhost:8092}
osmUrlServiceInstance: ${URL_OSM_NSLCM:http://34.69.239.30:8087}
aaiUrlGenerifVnf: ${AAI_GV_URL:http://localhost:8085}
